### ISSUE TITLE
How to run this alert script without using wordpress part ??

### ISSUE THREAD

**Issue by Ramlogics** [dziungles/Coinwink#10]
Hey , 

I need this script with core PHP , can you tell me what to replace ??

**Comment by giekaton** [comment]
For email alerts you need only backend_email.php and database table coinwink. Add some alerts manually to that db table and then run backend_email.php in your browser. It should work like this. You may need to edit email and db credentials and maybe use simple php mail function instead of the phpmailer which requires some wordpress files.
