### ISSUE TITLE
Feature request: refresh percentage-based alerts

### ISSUE THREAD

**Issue by neuromancer** [dziungles/Coinwink#15]
I'm monitoring certain coins with a X% of increment/decrement from the current price. Every time I receive an alert, I need to manually remove and re-create the alert to adjust the X% to current value. It will be nice a way to refresh this kind of alerts using the current price, without re-adding them.

**Comment by giekaton** [comment]
Hi neuromancer, thanks for the feedback.

To re-enable an activated alert, under your [Manage Alerts](https://coinwink.com/manage-alerts), simply click the activated (striked through) alert to re-enable it (or disable an active alert). There is no need to delete and re-create in order to re-enable the same alert.

Also, did you try using the [Portfolio](https://coinwink.com/manage-alerts) alerts? That way you can track percentage change for multiple coins at once. You won't need to reset these alerts as they reset every 24h automatically.

**Comment by neuromancer** [comment]
> To re-enable an activated alert, under your Manage Alerts, simply click the activated (striked through) alert to re-enable it (or disable an active alert).

I believe this only re-use the old value. Can you double check that? (if that's the case, feel free to close this issue)

> Also, did you try using the Portfolio alerts? That way you can track percentage change for multiple coins at once. You won't need to reset these alerts as they reset every 24h automatically.

That's a good idea. I will try it. Thanks :smile:

**Comment by neuromancer** [comment]
> To re-enable an activated alert, under your Manage Alerts, simply click the activated (striked through) alert to re-enable it (or disable an active alert). There is no need to delete and re-create in order to re-enable the same alert.

I'm receiving constants alerts for 5% increments in the AAVE token today but the price has changed very little. I don't think re-enable alerts is working as expected.

**Comment by giekaton** [comment]
It should work, always worked as expected. Please double check.

Coinwink is based on CMC data, where Aave increased today by more than 5%: https://coinmarketcap.com/currencies/aave/

**Comment by neuromancer** [comment]
This is my today log (removing my email):

```
Aave (LEND) alert
6 Aug 2020 12:27:01

Aave (LEND) alert
6 Aug 2020 11:27:01

Aave (LEND) alert
6 Aug 2020 11:02:01

Aave (LEND) alert
6 Aug 2020 10:52:02

Aave (LEND) alert
6 Aug 2020 09:57:01

Aave (LEND) alert
6 Aug 2020 09:52:02

Aave (LEND) alert
6 Aug 2020 09:32:02

Aave (LEND) alert
6 Aug 2020 09:27:02
```

**Comment by giekaton** [comment]
Did you re-enable them manually? If you re-enable the same 5% alert, you will receive it again, since Aave is still +5% in 24h. That's why these alerts are not re-enabling automatically (they would be flooding your mailbox/phone).

Only the portfolio alerts re-enable automatically, once in every 24h, so you can receive max 1 alert per 24h for each coin in your portfolio.

**Comment by giekaton** [comment]
As I now understand, you are talking about an alert that should activate after every X% increase.

After re-enabling, it should start tracking from the current CMC price, and not the one set during the initial alert creation.

Such functionality doesn't exist on Coinwink. It's an interesting idea though, maybe that's something for the future.

**Comment by giekaton** [comment]
Yes, that would be a useful upgrade, and also another user requested something similar. Can't promise exactly when, but this feature will be implemented on Coinwink.

**Comment by giekaton** [comment]
Hi,

Other users also had similar feedback for percentage alerts. The new Coinwink updates are already live and improve percentage alerts on a few different levels. That should also address your initial request.

For more info, check the blog post where it is explained in detail: https://coinwink.com/blog/new-updates-aug-2020

**Comment by neuromancer** [comment]
Thanks a lot :smile:
