### ISSUE TITLE
Feature request: Telegram alerts

### ISSUE THREAD

**Issue by neuromancer** [dziungles/Coinwink#16]
I know this can be a very ambitious feature, but I would love (and perhaps pay) for a Telegram bot with that will send me the Coinwink alerts. There is no need to control the Coinwink alerts, just the feature to receive the alerts using Telegram will be a nice thing to have.

**Comment by giekaton** [comment]
Hi,

As you say, this is a good to have feature, but if we start adding all these extra chat services, there is no end to them.

And actually, we would not gain much by adding these extra services. That's because e-mail + SMS is a classic well-tested combo that works under any conditions. It can alert you similary as Telegram or even better, but Telegram cannot alert you when e.g. you have no internet in your phone.

So e-mail + SMS is a simple combo that covers all possible situations.

Maybe in the future there can be some kind of a plugin system for adding extra services, but at the moment that's not a priority.

I'm closing the issue. Thanks for the idea :)
